name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          pip install jupyter-book
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: build book
        run: |
          jupyter-book build .

      - name: install ghp-import
        run: pip install ghp-import

      - name: deploy
        run: |
          ghp-import -n -p -f _build/html
